workout_data = {
    "8 Jun 2024": ["Running"],
    "10 Jun 2024": ["Russian Twist (Bodyweight)", "Toe Touch", "Side Plank", "Plank"],
    "12 Jun 2024": ["Goblet Squat", "Leg Press (Machine)", "Hack Squat (Machine)"],
    "15 Jun 2024": [
        "Bench Press (Dumbbell)",
        "Incline Chest Press (Machine)",
        "Seated Shoulder Press (Machine)",
        "Chest Fly (Machine)",
    ],
    "16 Jun 2024": ["Running"],
    "17 Jun 2024": [
        "Lying Leg Raise",
        "Mountain Climber",
        "Heel Taps",
        "Flutter Kicks",
    ],
    "18 Jun 2024": [
        "Lying Leg Curl (Machine)",
        "Leg Extension (Machine)",
        "Seated Calf Raise",
    ],
    "19 Jun 2024": [
        "Arnold Press (Dumbbell)",
        "Lateral Raise (Dumbbell)",
        "Triceps Dip (Weighted)",
        "Triceps Rope Pushdown",
        "Single Arm Tricep Extension (Dumbbell)",
    ],
    "20 Jun 2024": ["Russian Twist (Bodyweight)", "Toe Touch", "Side Plank", "Plank"],
    "21 Jun 2024": [
        "Seated Cable Row - Bar Grip",
        "Reverse Grip Lat Pulldown (Cable)",
        "Rear Delt Reverse Fly (Machine)",
        "Upright Row (Cable)",
    ],
    "22 Jun 2024": ["Running"],
    "23 Jun 2024": ["Goblet Squat", "Leg Press (Machine)", "Hack Squat (Machine)"],
    "24 Jun 2024": [
        "Shrug (Dumbbell)",
        "Preacher Curl (Barbell)",
        "Hammer Curl (Dumbbell)",
        "EZ Bar Biceps Curl",
    ],
    "27 Jun 2024": [
        "Lying Leg Raise",
        "Mountain Climber",
        "Heel Taps",
        "Flutter Kicks",
    ],
    "28 Jun 2024": [
        "Deadlift (Trap bar)",
        "Lying Leg Curl (Machine)",
        "Leg Extension (Machine)",
        "Seated Calf Raise",
    ],
    "29 Jun 2024": [
        "Bench Press (Dumbbell)",
        "Incline Chest Press (Machine)",
        "Seated Shoulder Press (Machine)",
        "Chest Fly (Machine)",
    ],
    "30 Jun 2024": ["Running"],
    "3 Jul 2024": ["Russian Twist (Bodyweight)", "Toe Touch", "Side Plank", "Plank"],
    "4 Jul 2024": [
        "Arnold Press (Dumbbell)",
        "Lateral Raise (Dumbbell)",
        "Triceps Dip (Weighted)",
        "Triceps Rope Pushdown",
        "Single Arm Tricep Extension (Dumbbell)",
    ],
    "5 Jul 2024": [
        "Upright Row (Cable)",
        "Shrug (Dumbbell)",
        "Hammer Curl (Dumbbell)",
        "Rear Delt Reverse Fly (Machine)",
    ],
    "8 Jul 2024": [
        "Seated Cable Row - Bar Grip",
        "Lat Pulldown - Close Grip (Cable)",
        "Preacher Curl (Machine)",
        "EZ Bar Biceps Curl",
    ],
    "10 Jul 2024": ["Goblet Squat", "Leg Press (Machine)", "Hack Squat (Machine)"],
    "16 Jul 2024": [
        "Lying Leg Raise",
        "Mountain Climber",
        "Heel Taps",
        "Flutter Kicks",
    ],
    "17 Jul 2024": [
        "Incline Chest Press (Machine)",
        "Seated Shoulder Press (Machine)",
        "Chest Fly (Machine)",
        "Arnold Press (Dumbbell)",
    ],
    "18 Jul 2024": [
        "Lying Leg Curl (Machine)",
        "Leg Extension (Machine)",
        "Seated Calf Raise",
    ],
    "26 Jul 2024": ["Burpee", "High Knees", "Mountain Climber", "Push Up"],
    "29 Jul 2024": ["Running"],
    "30 Jul 2024": [
        "Bench Press (Dumbbell)",
        "Lateral Raise (Dumbbell)",
        "Triceps Dip (Weighted)",
        "Triceps Rope Pushdown",
        "Single Arm Tricep Extension (Dumbbell)",
    ],
    "31 Jul 2024": [
        "Goblet Squat",
        "Leg Press (Machine)",
        "Squat (Machine)",
        "Lunge (Dumbbell)",
    ],
    "2 Aug 2024": ["Lying Leg Raise", "Heel Taps", "Flutter Kicks", "Plank"],
    "3 Aug 2024": ["Running"],
    "6 Aug 2024": ["Russian Twist (Bodyweight)", "Toe Touch", "Side Plank", "Plank"],
    "12 Aug 2024": [
        "Seated Cable Row - Bar Grip",
        "Reverse Grip Lat Pulldown (Cable)",
        "Rear Delt Reverse Fly (Machine)",
        "Upright Row (Cable)",
    ],
    "14 Aug 2024": [
        "Deadlift (Trap bar)",
        "Lying Leg Curl (Machine)",
        "Leg Extension (Machine)",
        "Seated Calf Raise",
    ],
    "17 Aug 2024": [
        "Lying Leg Raise",
        "Mountain Climber",
        "Heel Taps",
        "Flutter Kicks",
        "Plank",
    ],
    "20 Aug 2024": [
        "Shrug (Dumbbell)",
        "Preacher Curl (Barbell)",
        "Hammer Curl (Dumbbell)",
        "EZ Bar Biceps Curl",
        "Bench Press (Dumbbell)",
        "Incline Chest Press (Machine)",
        "Seated Shoulder Press (Machine)",
        "Chest Fly (Machine)",
    ],
    "22 Aug 2024": ["Russian Twist (Bodyweight)", "Toe Touch", "Side Plank", "Plank"],
    "24 Aug 2024": [
        "Goblet Squat",
        "Leg Press (Machine)",
        "Squat (Machine)",
        "Lunge (Dumbbell)",
    ],
    "25 Aug 2024": [
        "Arnold Press (Dumbbell)",
        "Lateral Raise (Dumbbell)",
        "Triceps Dip (Weighted)",
        "Triceps Rope Pushdown",
        "Single Arm Tricep Extension (Dumbbell)",
    ],
    "26 Aug 2024": [
        "Lying Leg Raise",
        "Mountain Climber",
        "Heel Taps",
        "Flutter Kicks",
        "Plank",
    ],
    "27 Aug 2024": [
        "Seated Cable Row - Bar Grip",
        "Reverse Grip Lat Pulldown (Cable)",
        "Rear Delt Reverse Fly (Machine)",
        "Upright Row (Cable)",
    ],
    "28 Aug 2024": [
        "Deadlift (Trap bar)",
        "Lying Leg Curl (Machine)",
        "Leg Extension (Machine)",
        "Seated Calf Raise",
    ],
    "29 Aug 2024": ["Russian Twist (Bodyweight)", "Toe Touch", "Side Plank", "Plank"],
    "30 Aug 2024": [
        "Bench Press (Dumbbell)",
        "Incline Chest Press (Machine)",
        "Seated Shoulder Press (Machine)",
        "Chest Fly (Machine)",
    ],
    "31 Aug 2024": ["Running"],
    "1 Sep 2024": [
        "Shrug (Dumbbell)",
        "Preacher Curl (Barbell)",
        "Hammer Curl (Dumbbell)",
        "EZ Bar Biceps Curl",
    ],
    "2 Sep 2024": [
        "Goblet Squat",
        "Leg Press (Machine)",
        "Squat (Machine)",
        "Lunge (Dumbbell)",
    ],
    "3 Sep 2024": [
        "Lying Leg Raise",
        "Mountain Climber",
        "Heel Taps",
        "Flutter Kicks",
        "Plank",
    ],
    "4 Sep 2024": [
        "Arnold Press (Dumbbell)",
        "Lateral Raise (Dumbbell)",
        "Triceps Dip (Weighted)",
        "Triceps Rope Pushdown",
        "Single Arm Tricep Extension (Dumbbell)",
    ],
    "5 Sep 2024": ["Russian Twist (Bodyweight)", "Toe Touch", "Side Plank", "Plank"],
    "6 Sep 2024": [
        "Deadlift (Trap bar)",
        "Lying Leg Curl (Machine)",
        "Leg Extension (Machine)",
        "Seated Calf Raise",
    ],
    "7 Sep 2024": ["Running"],
    "8 Sep 2024": [
        "Seated Cable Row - Bar Grip",
        "Reverse Grip Lat Pulldown (Cable)",
        "Rear Delt Reverse Fly (Machine)",
        "Upright Row (Cable)",
    ],
    "9 Sep 2024": [
        "Lying Leg Raise",
        "Mountain Climber",
        "Heel Taps",
        "Flutter Kicks",
        "Plank",
    ],
    "10 Sep 2024": [
        "Bench Press (Dumbbell)",
        "Incline Chest Press (Machine)",
        "Chest Fly (Machine)",
        "Seated Shoulder Press (Machine)",
    ],
    "11 Sep 2024": [
        "Goblet Squat",
        "Deadlift (Trap bar)",
        "Squat (Machine)",
        "Lunge (Dumbbell)",
    ],
    "12 Sep 2024": ["Russian Twist (Bodyweight)", "Toe Touch", "Side Plank", "Plank"],
    "13 Sep 2024": [
        "Shrug (Dumbbell)",
        "Preacher Curl (Barbell)",
        "Hammer Curl (Dumbbell)",
        "EZ Bar Biceps Curl",
    ],
    "14 Sep 2024": ["Running"],
    "15 Sep 2024": [
        "Arnold Press (Dumbbell)",
        "Lateral Raise (Dumbbell)",
        "Triceps Dip (Weighted)",
        "Triceps Rope Pushdown",
        "Single Arm Tricep Extension (Dumbbell)",
    ],
    "16 Sep 2024": [
        "Leg Press (Machine)",
        "Lying Leg Curl (Machine)",
        "Leg Extension (Machine)",
        "Seated Calf Raise",
    ],
    "17 Sep 2024": [
        "Lying Leg Raise",
        "Mountain Climber",
        "Heel Taps",
        "Flutter Kicks",
        "Plank",
    ],
    "18 Sep 2024": [
        "Seated Cable Row - Bar Grip",
        "Reverse Grip Lat Pulldown (Cable)",
        "Rear Delt Reverse Fly (Machine)",
        "Upright Row (Cable)",
    ],
    "20 Sep 2024": [
        "Goblet Squat",
        "Leg Press (Machine)",
        "Squat (Machine)",
        "Lunge (Dumbbell)",
    ],
    "22 Sep 2024": [
        "Bench Press (Dumbbell)",
        "Incline Chest Press (Machine)",
        "Chest Fly (Machine)",
        "Seated Shoulder Press (Machine)",
    ],
    "24 Sep 2024": [
        "Shrug (Dumbbell)",
        "Preacher Curl (Barbell)",
        "Hammer Curl (Dumbbell)",
        "EZ Bar Biceps Curl",
    ],
    "25 Sep 2024": ["Russian Twist (Bodyweight)", "Toe Touch", "Side Plank", "Plank"],
    "26 Sep 2024": [
        "Deadlift (Trap bar)",
        "Lying Leg Curl (Machine)",
        "Leg Extension (Machine)",
        "Seated Calf Raise",
    ],
    "27 Sep 2024": [
        "Arnold Press (Dumbbell)",
        "Lateral Raise (Dumbbell)",
        "Triceps Dip (Weighted)",
        "Triceps Rope Pushdown",
        "Single Arm Tricep Extension (Dumbbell)",
    ],
    "29 Sep 2024": [
        "Seated Cable Row - Bar Grip",
        "Reverse Grip Lat Pulldown (Cable)",
        "Rear Delt Reverse Fly (Machine)",
        "Upright Row (Cable)",
    ],
    "30 Sep 2024": [
        "Lying Leg Raise",
        "Mountain Climber",
        "Heel Taps",
        "Flutter Kicks",
    ],
    "1 Oct 2024": [
        "Goblet Squat",
        "Leg Press (Machine)",
        "Squat (Machine)",
        "Lunge (Dumbbell)",
    ],
    "3 Oct 2024": [
        "Bicep Curl (Dumbbell)",
        "Lateral Raise (Dumbbell)",
        "Single Arm Tricep Extension (Dumbbell)",
    ],
    "4 Oct 2024": ["Cycling"],
    "5 Oct 2024": [
        "Lying Leg Curl (Machine)",
        "Leg Extension (Machine)",
        "Seated Calf Raise",
    ],
    "6 Oct 2024": ["Cycling"],
    "7 Oct 2024": [
        "Bench Press (Dumbbell)",
        "Incline Chest Press (Machine)",
        "Chest Fly (Machine)",
        "Seated Shoulder Press (Machine)",
    ],
    "8 Oct 2024": ["Russian Twist (Bodyweight)", "Toe Touch", "Plank"],
    "9 Oct 2024": [
        "Shrug (Dumbbell)",
        "Preacher Curl (Barbell)",
        "Hammer Curl (Dumbbell)",
        "EZ Bar Biceps Curl",
    ],
    "11 Oct 2024": [
        "Goblet Squat",
        "Leg Press (Machine)",
        "Squat (Machine)",
        "Lunge (Dumbbell)",
    ],
    "12 Oct 2024": [
        "Arnold Press (Dumbbell)",
        "Lateral Raise (Dumbbell)",
        "Triceps Dip (Weighted)",
        "Triceps Rope Pushdown",
        "Single Arm Tricep Extension (Dumbbell)",
    ],
    "13 Oct 2024": ["Running"],
    "14 Oct 2024": [
        "Lying Leg Curl (Machine)",
        "Leg Extension (Machine)",
        "Seated Calf Raise",
        "Deadlift (Trap bar)",
    ],
    "16 Oct 2024": [
        "Bicep Curl (Dumbbell)",
        "Lateral Raise (Dumbbell)",
        "Single Arm Tricep Extension (Dumbbell)",
    ],
    "18 Oct 2024": [
        "Lying Leg Raise",
        "Mountain Climber",
        "Heel Taps",
        "Flutter Kicks",
        "Plank",
    ],
    "19 Oct 2024": [
        "Squat (Bodyweight)",
        "Lunge",
        "Glute Bridge",
        "Standing Calf Raise",
    ],
    "21 Oct 2024": ["Incline Push Ups", "Inverted Row", "Inverted row underhand"],
    "22 Oct 2024": ["Russian Twist (Bodyweight)", "Toe Touch", "Side Plank", "Plank"],
    "23 Oct 2024": [
        "Squat (Bodyweight)",
        "Lunge",
        "Glute Bridge",
        "Standing Calf Raise",
    ],
    "24 Oct 2024": [
        "Bicep Curl (Dumbbell)",
        "Lateral Raise (Dumbbell)",
        "Single Arm Tricep Extension (Dumbbell)",
    ],
    "25 Oct 2024": [
        "Lying Leg Raise",
        "Mountain Climber",
        "Heel Taps",
        "Flutter Kicks",
        "Plank",
    ],
    "26 Oct 2024": ["Incline Push Ups", "Bench Dip", "Cycling"],
    "28 Oct 2024": [
        "Squat (Bodyweight)",
        "Lunge",
        "Glute Bridge",
        "Standing Calf Raise",
    ],
    "29 Oct 2024": [
        "Bicep Curl (Dumbbell)",
        "Lateral Raise (Dumbbell)",
        "Single Arm Tricep Extension (Dumbbell)",
    ],
    "31 Oct 2024": [
        "Russian Twist (Bodyweight)",
        "Toe Touch",
        "Side Plank",
        "long lever plank",
    ],
    "1 Nov 2024": [
        "Seated Cable Row - Bar Grip",
        "Reverse Grip Lat Pulldown (Cable)",
        "Rear Delt Reverse Fly (Machine)",
        "Upright Row (Cable)",
    ],
    "2 Nov 2024": ["Elliptical Trainer"],
    "3 Nov 2024": [
        "Deadlift (Trap bar)",
        "Lying Leg Curl (Machine)",
        "Leg Extension (Machine)",
        "Seated Calf Raise",
    ],
    "4 Nov 2024": [
        "Lying Leg Raise",
        "Mountain Climber",
        "Heel Taps",
        "Flutter Kicks",
        "long lever plank",
    ],
    "5 Nov 2024": [
        "Bench Press (Dumbbell)",
        "Incline Bench Press (Dumbbell)",
        "Chest Fly (Machine)",
        "Seated Shoulder Press (Machine)",
    ],
    "6 Nov 2024": [
        "Counter Weight Squat",
        "Leg Press (Machine)",
        "Squat (Machine)",
        "Lunge (Dumbbell)",
    ],
    "7 Nov 2024": [
        "Shrug (Dumbbell)",
        "Preacher Curl (Barbell)",
        "Hammer Curl (Dumbbell)",
        "EZ Bar Biceps Curl",
    ],
    "11 Nov 2024": [
        "Russian Twist (Bodyweight)",
        "Toe Touch",
        "Side Plank",
        "long lever plank",
    ],
    "12 Nov 2024": [
        "Arnold Press (Dumbbell)",
        "Lateral Raise (Dumbbell)",
        "Triceps Dip (Weighted)",
        "Triceps Rope Pushdown",
        "Single Arm Tricep Extension (Dumbbell)",
    ],
    "13 Nov 2024": [
        "Lying Leg Curl (Machine)",
        "Leg Extension (Machine)",
        "Seated Calf Raise",
        "Deadlift (Trap bar)",
    ],
    "14 Nov 2024": [
        "Seated Cable Row - Bar Grip",
        "Reverse Grip Lat Pulldown (Cable)",
        "Rear Delt Reverse Fly (Machine)",
        "Upright Row (Cable)",
    ],
    "16 Nov 2024": ["Running"],
    "17 Nov 2024": [
        "Lying Leg Raise",
        "Mountain Climber",
        "Heel Taps",
        "Flutter Kicks",
    ],
    "18 Nov 2024": [
        "Counter Weight Squat",
        "Leg Press (Machine)",
        "Squat (Machine)",
        "Lunge (Dumbbell)",
    ],
    "19 Nov 2024": [
        "Bench Press (Dumbbell)",
        "Incline Chest Press (Machine)",
        "Chest Fly (Machine)",
        "Seated Shoulder Press (Machine)",
    ],
    "20 Nov 2024": [
        "Lying Leg Raise",
        "Russian Twist (Bodyweight)",
        "Side Plank",
        "long lever plank",
    ],
    "21 Nov 2024": [
        "Shrug (Dumbbell)",
        "Preacher Curl (Barbell)",
        "Hammer Curl (Dumbbell)",
        "EZ Bar Biceps Curl",
    ],
    "23 Nov 2024": ["Running"],
    "24 Nov 2024": [
        "Arnold Press (Dumbbell)",
        "Lateral Raise (Dumbbell)",
        "Triceps Dip (Weighted)",
        "Triceps Rope Pushdown",
        "Single Arm Tricep Extension (Dumbbell)",
    ],
    "25 Nov 2024": [
        "Lying Leg Curl (Machine)",
        "Leg Extension (Machine)",
        "Seated Calf Raise",
        "Deadlift (Trap bar)",
    ],
    "27 Nov 2024": [
        "Seated Cable Row - Bar Grip",
        "Reverse Grip Lat Pulldown (Cable)",
        "Rear Delt Reverse Fly (Machine)",
        "Upright Row (Cable)",
    ],
    "6 Dec 2024": [
        "Lying Leg Raise",
        "Russian Twist (Bodyweight)",
        "Side Plank",
        "long lever plank",
    ],
    "9 Dec 2024": [
        "Bench Press (Dumbbell)",
        "Incline Chest Press (Machine)",
        "Chest Fly (Machine)",
        "Seated Shoulder Press (Machine)",
    ],
    "11 Dec 2024": [
        "Counter Weight Squat",
        "Leg Press (Machine)",
        "Squat (Machine)",
        "Lunge (Dumbbell)",
    ],
    "13 Dec 2024": [
        "Shrug (Dumbbell)",
        "Preacher Curl (Barbell)",
        "Hammer Curl (Dumbbell)",
        "EZ Bar Biceps Curl",
    ],
    "17 Dec 2024": [
        "Lying Leg Raise",
        "Crunch",
        "Russian Twist (Bodyweight)",
        "Side Plank",
        "long lever plank",
    ],
    "18 Dec 2024": [
        "Lying Leg Curl (Machine)",
        "Leg Extension (Machine)",
        "Seated Calf Raise",
        "Deadlift (Trap bar)",
    ],
    "24 Dec 2024": ["Running"],
    "26 Dec 2024": [
        "Arnold Press (Dumbbell)",
        "Lateral Raise (Dumbbell)",
        "Triceps Dip (Weighted)",
        "Triceps Rope Pushdown",
        "Single Arm Tricep Extension (Dumbbell)",
        "Running",
    ],
    "27 Dec 2024": [
        "Lying Leg Raise",
        "Russian Twist (Weighted)",
        "Side Plank",
        "long lever plank",
        "Cable Crunch",
    ],
    "5 Jan 2025": ["Running"],
    "7 Jan 2025": [
        "Shrug (Dumbbell)",
        "Preacher Curl (Barbell)",
        "Hammer Curl (Dumbbell)",
        "EZ Bar Biceps Curl",
    ],
    "9 Jan 2025": [
        "Lying Leg Curl (Machine)",
        "Leg Extension (Machine)",
        "Seated Calf Raise",
        "Squat (Machine)",
    ],
    "10 Jan 2025": [
        "Lying Leg Raise",
        "Cable Crunch",
        "Russian Twist (Weighted)",
        "Side Plank",
        "long lever plank",
    ],
    "16 Jan 2025": [
        "Seated Cable Row - Bar Grip",
        "Reverse Grip Lat Pulldown (Cable)",
        "Rear Delt Reverse Fly (Machine)",
        "Pull Up (Assisted)",
    ],
    "17 Jan 2025": ["Running"],
    "18 Jan 2025": [
        "Lying Leg Raise",
        "Cable Crunch",
        "Russian Twist (Weighted)",
        "Side Plank",
        "long lever plank",
    ],
    "20 Jan 2025": [
        "Counter Weight Squat",
        "Leg Press (Machine)",
        "Lunge (Dumbbell)",
        "Deadlift (Trap bar)",
    ],
    "21 Jan 2025": [
        "Bench Press (Dumbbell)",
        "Incline Chest Press (Machine)",
        "Chest Fly (Machine)",
        "Seated Shoulder Press (Machine)",
    ],
    "22 Jan 2025": [
        "Lying Leg Raise",
        "Cable Crunch",
        "Russian Twist (Weighted)",
        "Side Plank",
        "long lever plank",
    ],
    "23 Jan 2025": [
        "Shrug (Dumbbell)",
        "Preacher Curl (Barbell)",
        "Chest Dip (Assisted)",
        "Hammer Curl (Dumbbell)",
    ],
    "24 Jan 2025": [
        "Arnold Press (Dumbbell)",
        "Lateral Raise (Dumbbell)",
        "Triceps Rope Pushdown",
        "Single Arm Tricep Extension (Dumbbell)",
        "EZ Bar Biceps Curl",
    ],
    "26 Jan 2025": ["Running"],
    "27 Jan 2025": [
        "Lying Leg Curl (Machine)",
        "Leg Extension (Machine)",
        "Seated Calf Raise",
        "Squat (Machine)",
    ],
    "28 Jan 2025": [
        "Lying Leg Raise",
        "Russian Twist (Weighted)",
        "Side Plank",
        "long lever plank",
        "Cable Crunch",
    ],
    "29 Jan 2025": ["Cycling"],
    "4 Feb 2025": [
        "Seated Cable Row - Bar Grip",
        "Pull Up (Assisted)",
        "Chest Fly (Machine)",
        "Seated Shoulder Press (Machine)",
    ],
    "10 Feb 2025": [
        "Bench Press (Dumbbell)",
        "Lat Pulldown - Close Grip (Cable)",
        "Triceps Rope Pushdown",
        "Preacher Curl (Barbell)",
        "Treadmill",
    ],
    "11 Feb 2025": [
        "Shrug (Dumbbell)",
        "Arnold Press (Dumbbell)",
        "Deadlift (Trap bar)",
        "Incline Chest Press (Machine)",
    ],
    "12 Feb 2025": [
        "Lying Leg Raise",
        "Leg Press (Machine)",
        "Russian Twist (Weighted)",
        "EZ Bar Biceps Curl",
    ],
    "13 Feb 2025": [
        "Lateral Raise (Dumbbell)",
        "Rear Delt Reverse Fly (Machine)",
        "Iso-Lateral Chest Press (Machine)",
        "Seated Calf Raise",
    ],
    "17 Feb 2025": [
        "Leg Extension (Machine)",
        "Bench Press (Dumbbell)",
        "Hammer Curl (Dumbbell)",
        "Triceps Dip (Assisted)",
        "Treadmill",
    ],
    "18 Feb 2025": [
        "Lying Leg Curl (Machine)",
        "Seated Cable Row - V Grip (Cable)",
        "Triceps Rope Pushdown",
        "Cable Crunch",
    ],
    "19 Feb 2025": [
        "Preacher Curl (Machine)",
        "Incline Chest Press (Machine)",
        "Side Plank",
        "long lever plank",
        "Treadmill",
    ],
    "24 Feb 2025": [
        "Squat (Machine)",
        "Seated Shoulder Press (Machine)",
        "Lat Pulldown - Close Grip (Cable)",
        "Chest Fly (Machine)",
    ],
    "26 Feb 2025": [
        "EZ Bar Biceps Curl",
        "Deadlift (Trap bar)",
        "Lying Leg Raise",
        "Russian Twist (Weighted)",
    ],
    "27 Feb 2025": [
        "Arnold Press (Dumbbell)",
        "Lateral Raise (Dumbbell)",
        "Iso-Lateral Chest Press (Machine)",
        "Cable Crunch",
        "Treadmill",
    ],
    "28 Feb 2025": [
        "Seated Calf Raise",
        "Pull Up (Assisted)",
        "Shrug (Dumbbell)",
        "Leg Extension (Machine)",
    ],
    "4 Mar 2025": [
        "Bench Press (Dumbbell)",
        "Preacher Curl (Machine)",
        "Rear Delt Reverse Fly (Machine)",
        "Side Plank",
    ],
    "5 Mar 2025": [
        "Seated Shoulder Press (Machine)",
        "Reverse Grip Lat Pulldown (Cable)",
        "Triceps Dip (Assisted)",
        "Treadmill",
    ],
    "7 Mar 2025": [
        "Lunge (Dumbbell)",
        "Upright Row (Cable)",
        "long lever plank",
        "Single Arm Tricep Extension (Dumbbell)",
    ],
    "11 Mar 2025": [
        "Leg Press (Machine)",
        "Hammer Curl (Dumbbell)",
        "Incline Chest Press (Machine)",
        "Iso-Lateral Low Row",
    ],
    "12 Mar 2025": [
        "Lateral Raise (Dumbbell)",
        "Chest Fly (Machine)",
        "Lying Leg Raise",
        "Treadmill",
    ],
    "13 Mar 2025": [
        "Deadlift (Trap bar)",
        "Arnold Press (Dumbbell)",
        "Triceps Rope Pushdown",
        "Russian Twist (Weighted)",
    ],
    "14 Mar 2025": [
        "Lying Leg Curl (Machine)",
        "EZ Bar Biceps Curl",
        "Iso-Lateral Chest Press (Machine)",
        "Seated Cable Row - V Grip (Cable)",
    ],
}


def generate_workout_insertion_commands():
    sql_commands = []

    for date, exercises in workout_data.items():
        exercises = "', '".join(exercises)
        exercises = "('" + exercises + "')"
        sql_commands.append(
            f"INSERT INTO workouts (date, exercise_ids) VALUES ('{date}', (SELECT ARRAY(SELECT id from exercises where name in {exercises})));"
        )

    print("\n".join(sql_commands))


generate_workout_insertion_commands()
